project:
  type: website

website:
  title: "LEP on Income Levels"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home

      # Dropdown
      - text: More
        menu:
          - insights.qmd

      - model.qmd
      - sources.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



